name: project_template
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1 #网络请求
  dio_cookie_manager: ^3.2.0 #cookie管理
  cookie_jar: ^4.0.8 #cookie管理
  webview_flutter: ^4.11.0 #webView组件
  cached_network_image: ^3.4.1 #图片下载缓存库
  flutter_html: ^3.0.0 #html标签解析
  get: ^4.7.2 #状态管理
  html: ^0.15.6
  loading_animation_widget: ^1.3.0 #全局加载动画
  shared_preferences: any #数据持久化缓存 //2.5.3
  bot_toast: ^4.1.3  #Toast提示
  logger: ^2.5.0        #log日志打印
  auto_size_text: ^3.0.0 #自适应字体大小
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5 #加载动画
  hive: ^2.2.3 #数据库
  hive_flutter: ^1.1.0 #数据库
  #introduction_screen: ^3.1.17 #引导页
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/common/