name: project_template
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1 #网络请求
  dio_cookie_manager: ^3.2.0 #cookie管理
  cookie_jar: ^4.0.8 #cookie管理
  path_provider: ^2.1.5 #获取沙盒路径
  uuid: ^4.5.1 #生成UUID
  flutter_udid: ^4.0.0 #UDID
  device_info_plus: ^11.4.0 #设备信息
  video_player: ^2.9.5 #官方播放器插件
  chewie: ^1.11.3  #基于video_payer封装的播放器
  pull_to_refresh: ^2.0.0 #上下拉刷新 7.64587525
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0  #创建数据模型配合json_serializable,build_runner使用
  fluttertoast: ^8.2.12      #Toast提示
  bot_toast: ^4.1.3  #Toast提示
  flutter_easyloading: ^3.0.5 # HUD
  card_swiper: ^3.0.1  #轮播图
  flutter_screenutil: ^5.9.3 #适配屏幕和字体大小的flutter插件。让你的UI在不同的屏幕尺寸上显示合理的布局
  flutter_gen_runner: ^5.10.0 #资源路径自动生成路径 dart run build_runner build
  convex_bottom_bar: ^3.2.0 #底部导航栏
  logger: ^2.5.0        #log日志打印
  connectivity_plus: ^6.1.4 #网络检测状态
  cached_network_image: ^3.4.1 #图片下载缓存库
  flutter_staggered_grid_view: ^0.7.0 #瀑布流
  #status_bar_control: ^3.2.1 #状态栏控件，可让您控制 iOS 和 Android 上的状态栏颜色、样式（主题）、可见性和半透明属性。
  transparent_image: ^2.0.1 #淡入淡出图片
  webview_flutter: ^4.11.0 #webView组件
  loading_animation_widget: ^1.3.0 #全局加载动画
  shared_preferences: any #数据持久化缓存 //2.5.3
  fl_chart: ^0.71.0 #图表库
  flex_color_scheme: ^8.2.0 #主题
  buttons_tabbar: ^1.3.15 #按钮tabbar
  auto_size_text: ^3.0.0 #自适应字体大小
  #tab_indicator_styler //选项卡切换指示器
  pin_code_fields: ^8.0.1 #6格验证码
  city_pickers: ^1.3.0 #省市区三级联动
  crypto: ^3.0.6 #MD5加密和SHA
  hive: ^2.2.3 #NoSQL数据库  flutter packages pub run build_runner build
  hive_flutter: ^1.1.0 #hive NoSQL数据库管理
  flutter_spinkit: ^5.2.1 #loading动画
  scrollview_observer: ^1.26.0 #监听滚动视图中正在显示的子部件 支持滚动到指定下标位置
  provider: ^6.1.5        #状态管理
  input_quantity: ^2.5.1 #输入数量 左右加减按钮
  comment_tree: ^0.3.0  #评论列表和评论回复列表二级树
  intl: ^0.20.2 #提供国际化和本地化设施，包括消息翻译、复数和性别、日期/数字格式和解析以及双向文本。
  screen_brightness: ^2.1.3 #屏幕亮度修改
  html: ^0.15.6
  introduction_screen: ^3.1.17 #引导页
  get: ^4.7.2
  awesome_notifications: ^0.10.1 #远程/本地推送通知自定义布局 Build Libraries for Distributio 要设置为NO
  web_socket_channel: ^3.0.3 #webSocket
  animated_bottom_navigation_bar: ^1.4.0 #底部导航栏
  rxdart: ^0.28.0 # 配合Bloc使用
  equatable: ^2.0.7  #增强组件相等性判断 配合Bloc使用
  flutter_bloc: ^9.1.1 #Bloc状态管理
  bloc: ^9.0.0
  go_router: ^15.1.1 #路由 配合Bloc使用

  #flutter_native_splash: ^2.4.6 #启动页 生成启动屏：dart run flutter_native_splash:create
  #或删除启动屏：dart run flutter_native_splash:remove
  #图标 512x512 px 启动图 1242x2436 px

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5 #数据模型序列化 json_annotation,build_runner使用
  build_runner: ^2.4.15 #数据模型生成
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/barrage/
    - assets/images/common/
    - assets/images/tabs/
    - assets/vectors/
    - assets/fonts/
    - assets/depth.json
    - assets/chatData.json
  fonts:
#    - family: tvIcon   #指定一个字体名 根据自己的需求定义
#      fonts:
#        - asset: assets/fonts/iconfont.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900


# 应用图标配置
#f#lutter_native_splash:
#  # 为 Android 配置图标
 # android: true
#  # 为 iOS 配置图标
 # ios: true
 # # 为 web 配置图标
 # web: true
 # # 设置启动图的图片路径
 # image:  "assets/images/launch_image.png"
  ##color_android: "#ffffff"
  ##color_ios: "#ffffff"
  #background_image_android: "assets/images/launch_image.png"
  #background_image_ios: "assets/images/launch_image.png"
  ## image_ios: "assets/launcher/android.png"
  #android_12:
  #  image: "assets/images/Icon-App-512x512.png"
  #  icon_background_color: "#324ea1"
   # # android min sdk min:16, default 21
  #  # min_sdk_android: 21
